#!/bin/bash
APPDIR="$(dirname "$(readlink -f "$0")")"
export PATH="${APPDIR}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
export PROJ_DATA="${APPDIR}/usr/share/proj"
exec "${APPDIR}/usr/bin/sentinel2-scraper" "$@"
